version: '3'
services:

  server:
    build: ./
    container_name: server
    image: zogxray/micro-services-hub
    networks:
      hub:
        ipv4_address: 10.5.0.111
    volumes:
      - ./:/app
    environment:
      - FRONT_SERVER_PORT=9502
      - SERVICE_SERVER_PORT=9503
      - PING_SERVER_PORT=9504
      - REDIS_PORT=6380

  client1:
    build: ./test/client
    container_name: client1
    image: zogxray/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.122
    depends_on:
      - server
#    volumes:
#    - ./test/client:/app

  client2:
    build: ./test/client
    container_name: client2
    image: zogxray/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.123
    depends_on:
      - server
#    volumes:
#    - ./test/client:/app


  service1:
    build: ./test/service
    container_name: service1
    image: zogxray/micro-services-service
    networks:
      hub:
        ipv4_address: 10.5.0.116
    depends_on:
      - server
#    volumes:
#    - ./test/service:/app

  service2:
    build: ./test/service
    container_name: service2
    image: zogxray/micro-services-service
    networks:
      hub:
        ipv4_address: 10.5.0.117
    depends_on:
      - server
#    volumes:
#    - ./test/service:/app

networks:
  hub:
    external: true
#docker network create --gateway 10.5.0.1 --subnet 10.5.0.0/24 hub