version: '3'
services:

  server:
    build: ./
    container_name: server
    image: zogxray/micro-services-hub
    environment:
     - SERVER_LIVE_INTERVAL=30
     - CLIENT_SERVER_ADDR=0.0.0.0
     - CLIENT_SERVER_PORT=9503
     - SERVICE_SERVER_ADDR=0.0.0.0
     - SERVICE_SERVER_PORT=9502
     - BASE_SERVER_ADDR=0.0.0.0
     - BASE_SERVER_PORT=9501
     - PHP_MEMORY_LIMIT=1024M
    networks:
      hub:
        ipv4_address: 10.5.0.111
    volumes:
      - ./:/app

  client1:
    build: ./test/client
    container_name: client1
    image: zogxray/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.22
    depends_on:
      - server
    volumes:
      - ./test/client:/app
#
#  client2:
#    build: ./test/client
#    container_name: client2
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.23
#    depends_on:
#      - server
#    volumes:
#      - ./test/client:/app
#
#  client3:
#    build: ./test/client
#    container_name: client3
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.24
#    depends_on:
#      - server
#    volumes:
#      - ./test/client:/app
#
#  client4:
#    build: ./test/client
#    container_name: client4
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.25
#    depends_on:
#      - server
#    volumes:
#      - ./test/client:/app
#
#  client5:
#    build: ./test/client
#    container_name: client5
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.26
#    depends_on:
#      - server
#    volumes:
#      - ./test/client:/app
#
#  client6:
#    build: ./test/client
#    container_name: client6
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.27
#    depends_on:
#    - server
#    volumes:
#    - ./test/client:/app
#
#  client7:
#    build: ./test/client
#    container_name: client7
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.28
#    depends_on:
#    - server
#    volumes:
#    - ./test/client:/app
#
#  client8:
#    build: ./test/client
#    container_name: client8
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.29
#    depends_on:
#    - server
#    volumes:
#    - ./test/client:/app
#
#  client9:
#    build: ./test/client
#    container_name: client9
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.30
#    depends_on:
#    - server
#    volumes:
#    - ./test/client:/app
#
#  client10:
#    build: ./test/client
#    container_name: client10
#    image: zogxray/micro-services-client
#    networks:
#      hub:
#        ipv4_address: 10.5.0.31
#    depends_on:
#    - server
#    volumes:
#    - ./test/client:/app

  service1:
    build: ./test/service
    container_name: service1
    image: zogxray/micro-services-service
    networks:
      hub:
        ipv4_address: 10.5.0.116
    depends_on:
      - server
    volumes:
    - ./test/service:/app

#  service2:
#    build: ./test/service
#    container_name: service2
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.117
#    depends_on:
#      - server
##    volumes:
##    - ./test/service:/app
#
#  service3:
#    build: ./test/service
#    container_name: service3
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.118
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app
#
#  service4:
#    build: ./test/service
#    container_name: service4
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.119
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app
#
#  service5:
#    build: ./test/service
#    container_name: service5
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.120
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app
#
#  service6:
#    build: ./test/service
#    container_name: service6
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.121
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app
#
#  service7:
#    build: ./test/service
#    container_name: service7
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.122
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app
#
#  service8:
#    build: ./test/service
#    container_name: service8
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.123
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app
#
#  service9:
#    build: ./test/service
#    container_name: service9
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.124
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app
#
#  service10:
#    build: ./test/service
#    container_name: service10
#    image: zogxray/micro-services-service
#    networks:
#      hub:
#        ipv4_address: 10.5.0.125
#    depends_on:
#    - server
##    volumes:
##    - ./test/service:/app

networks:
  hub:
    external: true
#docker network create --gateway 10.5.0.1 --subnet 10.5.0.0/24 hub